### ISSUE TITLE
Ogone eCommerce error "unknown order/1/s/"

### ISSUE THREAD

**Issue by pecuchet** [pronamic/wp-pronamic-ideal#100] opened 2016-09-17 13:54 UTC
Although my passphrases and the hash algorithm match with my ogone configuration, I keep having that same error. I'm using pronamic-ideal with gravity forms. Problem is, I can't seem to find where the error comes from...

**Comment by rvdsteege** [comment] 2016-09-19 06:55
The error message is not caused by an issue in the Pronamic iDEAL plugin and therefore I hereby close this issue. To `var_dump()` the fields which are being submitted to Ingenico for inspection, please see https://github.com/wp-pay-gateways/ogone/blob/master/src/OrderStandard/Gateway.php#L184 and check the generated signature in https://github.com/wp-pay-gateways/ogone/blob/master/src/Security.php#L99-L126 (the `wp-pay-gateways/ogone/` directory is in `/wp-content/plugins/pronamic-ideal/vendor/wp-pay-gateways/ogone/`).

For support, please send your question to support@pronamic.nl and include your support license key and any necessary login details to reproduce and research the issue for you (i.e. WordPress admin account, FTP, Ingenico dashboard).

**Closed by rvdsteege** 2016-09-19 06:55 UTC

**Comment by pecuchet** [comment] 2016-09-19 14:28
Ok, thanks,

I may have found the problem though. My Ogone account is currently in test mode, I accordingly set the mode to ```Test``` in the ```Payment Gateway Configuration``` of iDeal, this should sent my form to ```https://secure.ogone.com/ncol/test/orderstandard.asp```, and not ```https://secure.ogone.com/ncol/prod/orderstandard.asp``` as it is currently doing in https://github.com/wp-pay-gateways/ogone/blob/master/src/Config.php#L48-L55

**Comment by rvdsteege** [comment] 2016-09-20 06:36
Ah sorry, that is a known bug and has already been solved in https://github.com/wp-pay-gateways/ogone/commit/8d7866121abb355168a384442d3ca01eac146235 (but unfortunately hasn't found its way into a plugin release yet). The next plugin update will include this bug fix.
